### ISSUE TITLE
Text datasets and README

### ISSUE THREAD

**Issue by KeepRunning2023** [Reza-Zhu/MBF#1]
Hello, thank you for sharing your work. Could you share the text files that you used to build the multimodal dataset?  Moreover, could you provide a README file to guide the reproduction of your work? If you could help, I will appreciate very much. Look forward to your reply.  : )

**Comment by Reza-Zhu** [comment]
Sorry for my late response. I have updated the README file and displayed the code to generate text files for University-1652. If you have any questions feel free to contact me. I will continue to improve the code.

**Comment by KeepRunning2023** [comment]
Thank you very much.
