### ISSUE TITLE
Training code on SUES-200

### ISSUE THREAD

**Issue by mrwangyou** [Reza-Zhu/MBF#6]
Hi Runzhe,

Thank you for your outstanding work on UAV Geo-localization. I noticed that the model is trained on the SUES-200 dataset and the results are reported in your paper. Could you kindly share the training code for the SUES-200 dataset?

Thank you very much!

**Comment by Reza-Zhu** [comment]
SUES-200 sentences generation and train, eval code have been uploaded. Please check the lastest repository.

Any questions are welcome！

**Comment by mrwangyou** [comment]
Thanks for your response. That would be really helpful for my work.
